import { v4 as uuidv4 } from "uuid";

const dummyText =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam ultrices sagittis orci a scelerisque purus. Nisl purus in mollis nunc sed id semper risus in. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Amet cursus sit amet dictum sit amet justo donec enim. Cras ornare arcu dui vivamus. In egestas erat imperdiet sed euismod nisi. Facilisis gravida neque convallis a cras. Congue nisi vitae suscipit tellus mauris a diam. Mattis ullamcorper velit sed ullamcorper morbi. Massa sed elementum tempus egestas sed sed risus pretium. Sed tempus urna et pharetra pharetra massa massa. Magnis dis parturient montes nascetur ridiculus mus mauris. Amet luctus venenatis lectus magna. Integer enim neque volutpat ac tincidunt vitae semper quis.";

export const mockProducts = [
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3q2Kh44",
    imageAlt: "Typewriter",
    title: "Vintage Typewriter",
    shortDescription: "Post awesome stories about UI design and Web Dev",
    description: dummyText,
    brand: "Random brand",
    price: 49.5,
    tag: null,
    tagline: "Eligible for free shipping to Mars or somewhere else",
    rating: 4.1,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3aFdxax",
    imageAlt: "Kitten",
    title: "Timesaving kitten app",
    shortDescription: "Save months on development. Playful, cute, cheap!",
    description: dummyText,
    brand: "Random brand",
    price: 128.99,
    tag: null,
    tagline: "Eligible for nothing :(",
    rating: 4.8,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3cQOm7Q",
    imageAlt: "Plugs",
    title: null,
    shortDescription:
      "Plastic useless plugs and tubes for high fidelity prototyping. Fit and Eat!",
    description: dummyText,
    brand: "Random brand",
    price: 12.48,
    tag: "50% off",
    tagline: "Worldwide shipping available. Buyers protection possible!",
    rating: 4.9,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/2N8ch7F",
    imageAlt: "Drink",
    title: "Some title",
    shortDescription:
      "Creativity stimulating lotion. Drink every morning to generate better ideas!",
    description: dummyText,
    brand: "Random brand",
    price: 12.48,
    tag: null,
    tagline: "Worldwide shipping available. Buyers protection possible!",
    rating: 4.9,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3jpqcT9",
    imageAlt: "Items",
    title: null,
    shortDescription: "Prototyping items to create a lot of useless things",
    description: dummyText,
    brand: "Random brand",
    price: 128.99,
    tag: null,
    tagline: "Eligible for nothing :(",
    rating: 4.8,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3rvjspr",
    imageAlt: "Clothing",
    title: null,
    shortDescription: null,
    description: dummyText,
    brand: "Random brand",
    price: 13.95,
    tag: null,
    tagline: "1258 bids, 358 watchers $5.95 for shipping",
    rating: 4.5,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/2MZy2Xo",
    imageAlt: "Envelope",
    title: null,
    shortDescription:
      "Envelope, Stripes, Pencil and etc. Purchase this kit today and feel OKAY",
    description: dummyText,
    brand: "Random brand",
    price: 9.5,
    tag: null,
    tagline: "Eligible for free shipping to Mars or somewhere else",
    rating: 4.7,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3cN3PWf",
    imageAlt: "Teapot",
    title: null,
    shortDescription:
      "Professional teadrinking set for every designer and developer",
    description: dummyText,
    brand: "Random brand",
    price: 128.99,
    tag: null,
    tagline: "Eligible for nothing :(",
    rating: 4.8,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/2LrxGIA",
    imageAlt: "Plant",
    title: null,
    shortDescription: "One string Bonsal description",
    description: dummyText,
    brand: "Random brand",
    price: 11.68,
    tag: null,
    tagline: "Worldwide shipping available. Buyers protection possible!",
    rating: 4.9,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3tAvG21",
    imageAlt: "Nail polish",
    title: null,
    shortDescription:
      "Simply best item in town to shine bright with your nine inch nails",
    description: dummyText,
    brand: "Random brand",
    price: 1.25,
    tag: "Cool Deal",
    tagline: "Eligible for free shipping to Mars or somewhere else",
    rating: 4.7,
    reviewCount: 1,
  },
  {
    id: uuidv4(),
    imageUrl: "https://bit.ly/3tAE3dR",
    imageAlt: "Brush",
    title: null,
    shortDescription:
      "KISTOCHKI & KRASIBO. Top cosmetics brand from Chelyabinsk is here!",
    description: dummyText,
    brand: "Random brand",
    price: 23.25,
    tag: null,
    tagline: "1258 bids, 359 watchers $5.95 for shipping",
    rating: 4.5,
    reviewCount: 1,
  },
];

export const searchTags = [
  "worldwide shipping",
  "under $50 item",
  "plastic plugs",
  "pucker shoes",
  "vintage typewriter",
];
